# Generated by Django 2.2.26 on 2022-03-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CR8', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievementCriteriaExpectedVal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='achievementType',
            field=models.CharField(default='currency', max_length=10),
        ),
    ]
